import { ReactQueryClientProvider } from '@/components/react-query-client-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { twJoin } from 'tailwind-merge'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	sidebar,
}: Readonly<{
	children: React.ReactNode
	sidebar: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={twJoin(inter.className, 'flex')}>
				<ReactQueryClientProvider>
					{sidebar}
					{children}
				</ReactQueryClientProvider>
			</body>
		</html>
	)
}
